# app/services/learning_path.py
learning_resources = {
    "Python": "https://www.learnpython.org/",
    "Flask": "https://flask.palletsprojects.com/en/latest/",
    "Django": "https://docs.djangoproject.com/en/stable/",
    "REST API": "https://www.codecademy.com/learn/learn-api-development",
    "MySQL": "https://www.w3schools.com/mysql/",
    "Git": "https://www.atlassian.com/git/tutorials/learn-git-with-bitbucket-cloud",
    "HTML": "https://www.w3schools.com/html/",
    "CSS": "https://www.w3schools.com/css/",
    "JavaScript": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
    "React": "https://reactjs.org/docs/getting-started.html",
    "Tailwind CSS": "https://tailwindcss.com/docs/installation",
    "SQL": "https://www.w3schools.com/sql/",
    "Excel": "https://exceljet.net/",
    "pandas": "https://pandas.pydata.org/docs/",
    "NumPy": "https://numpy.org/learn/",
    "scikit-learn": "https://scikit-learn.org/stable/tutorial/index.html",
    "TensorFlow": "https://www.tensorflow.org/learn",
    "Jupyter": "https://jupyter.org/try",
    "Airflow": "https://airflow.apache.org/docs/",
    "ETL": "https://www.datacamp.com/tutorial/extract-transform-load-etl",
    "BigQuery": "https://cloud.google.com/bigquery/docs/introduction",
    "Spark": "https://spark.apache.org/docs/latest/",
    "Linux": "https://ubuntu.com/tutorials/command-line-for-beginners",
    "Docker": "https://docs.docker.com/get-started/",
    "Kubernetes": "https://kubernetes.io/docs/tutorials/",
    "CI/CD": "https://www.redhat.com/en/topics/devops/what-is-ci-cd",
    "AWS": "https://aws.amazon.com/training/",
    "Terraform": "https://developer.hashicorp.com/terraform/intro",
    "Azure": "https://learn.microsoft.com/en-us/training/azure/",
    "GCP": "https://cloud.google.com/training",
    "Bash": "https://linuxconfig.org/bash-scripting-tutorial-for-beginners",
    "Networking": "https://www.geeksforgeeks.org/computer-network-tutorials/",
    "Firewalls": "https://www.cloudflare.com/learning/ddos/what-is-a-firewall/",
    "Penetration Testing": "https://owasp.org/www-project-web-security-testing-guide/",
    "Wireshark": "https://www.wireshark.org/docs/",
    "PyTorch": "https://pytorch.org/tutorials/",
    "Deep Learning": "https://www.deeplearning.ai/",
    "Figma": "https://help.figma.com/hc/en-us/articles/360040318613-Learn-Design-with-Figma",
    "Sketch": "https://www.sketch.com/learn/",
    "Wireframing": "https://careerfoundry.com/en/blog/ux-design/how-to-make-a-wireframe/",
    "User Research": "https://www.nngroup.com/topic/user-research/",
    "Adobe XD": "https://helpx.adobe.com/xd/tutorials.html",
    "Agile": "https://www.atlassian.com/agile",
    "Scrum": "https://www.scrum.org/resources/what-is-scrum",
    "JIRA": "https://www.atlassian.com/software/jira/guides",
    "Communication": "https://www.coursera.org/learn/wharton-communication-skills",
    "Business Analysis": "https://www.investopedia.com/terms/b/business-analysis.asp",
    "Test Case Design": "https://www.guru99.com/test-case.html",
    "Selenium": "https://www.selenium.dev/documentation/en/",
    "Postman": "https://learning.postman.com/",
    "Bug Tracking": "https://www.javatpoint.com/bug-tracking-tools",
    "C#": "https://learn.microsoft.com/en-us/dotnet/csharp/",
    "Unity": "https://learn.unity.com/",
    "Game Design": "https://www.gamedesigning.org/learn/",
    "Physics": "https://www.khanacademy.org/science/physics",
    "3D Modeling": "https://www.blender.org/support/tutorials/"
}

def get_learning_path(skills):
    """คืนลิสต์แหล่งเรียนรู้เรียงตามลำดับสำหรับทักษะที่ยังไม่มี"""
    return [
        {"skill": skill, "url": learning_resources.get(skill, "#")}
        for skill in skills
    ]
